[package]
name = "mikaboshi"
version = "0.1.0"
edition = "2018"

[dependencies]
sowngwala = { git = "https://github.com/minagawah/sowngwala", version = "0.1.0" }

[dev-dependencies]
approx_eq = "0.1.8"
